### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by ghost** [tweekmonster/nmux#1]
Environment:

- Chrome 54.0.2840.98
- macOS 10.12.1
- NVIM v0.2.0-11-gf2c6cc2 Build type: Dev
- go version go1.7.3 darwin/amd64

Repro:

1.  $ nmux  --addr localhost:8080
2.    Go to http://localhost:8080/ in Chrome
3.    Type ixxx

Result: 

![untitled](https://cloud.githubusercontent.com/assets/33411/20771275/9df0d5cc-b6fd-11e6-8efe-da8c1fbaba9b.png)

Expect: 

First line has characters "xxx".

Stdout from lo nmux:

```
$ nmux  --addr localhost:8080
2016/11/30 13:08:04 GET - /
2016/11/30 13:08:04 GET - /const.js
2016/11/30 13:08:04 GET - /string.js
2016/11/30 13:08:04 GET - /bytes.js
2016/11/30 13:08:04 GET - /animate.js
2016/11/30 13:08:04 GET - /keyboard.js
2016/11/30 13:08:04 GET - /screen.js
2016/11/30 13:08:04 GET - /socket.js
2016/11/30 13:08:04 GET - /nmux.js
2016/11/30 13:08:04 Connection from: http://localhost:8080
2016/11/30 13:08:07 Mouse Enabled
2016/11/30 13:08:07 Mode change: insert
```

In case my init.vim is a fault, I also ran an edited version of numx with nvim command line flags  `-u NORC`.  This does not fix the issue.

**Comment by tweekmonster** [comment]
I'm able to reproduce this now.  I haven't completely confirmed it yet, but it's apparently caused by cterm colors not being translated to RGB or the named colors aren't being translated.  If you can tolerate not seeing what you type, type this in the browser:

```
:highlight Normal guifg=#ffffff guibg=#000000
```

And the text should appear.

**Comment by tweekmonster** [comment]
This is mostly fixed now.  The issue was that nvim sends `-1` for unset colors.  There seems to still be issues with the cursor picking up the wrong color sometimes, but doesn't seem to happen when the `gui*` colors are set properly.  In any case, you can see text now!
