### ISSUE TITLE
nmux is blurry on retina displays

### ISSUE THREAD

**Issue by nhooyr** [tweekmonster/nmux#7]
title

**Comment by tweekmonster** [comment]
@nhooyr the WebUI was updated.  I was only able to emulate it since since I don't have an HiDPI screen.  The performance really sucks if 2D hardware acceleration isn't enabled for your browser.

Keeping this open until I get a chance to update the macOS client.

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
